services:
  app:
    build: ./src-app
    container_name: room6-pentest-app
    ports:
      - "3008:3000"
    volumes:
      - ./src-app:/app
    working_dir: /app
    command: npm start
    networks:
      - room6-network

networks:
  room6-network:
    driver: bridge
